"""
20_report.py
============
Generates analysis/results/area_estimation_report.html from the corrected
estimation JSONs. This REPLACES the previously hand-authored, orphaned report
whose PPI conclusions were based on an IID variance calculation (review Finding 2)
and on 474 non-deduplicated rows (Finding 1).

Reads (all now carry a top-level "sensitivity_adjudication": {ARP, SVM}):
  results/area_estimation.json        (Olofsson + PPI vs proper stratified, 3-class)
  results/area_estimation_efg.json    (EFG x class, estimability flags)
  results/ppi_continuous.json         (continuous-predictor PPI vs stratified)
  results/degradation_index.json      (mean true degradation, PPI vs stratified)

Headline correction: with the PROPER stratified baseline and the area-calibrated
population, PPI++ does NOT beat the design baseline for any estimand. The report
states this plainly and shows both adjudication arms as the interpreter-variability
sensitivity.

Run: C:/Users/geethen.singh/.pixi/envs/geo/python.exe analysis/20_report.py
"""
import json, os, html

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")
Z = 1.959963984540054


def load(name):
    return json.load(open(os.path.join(RESULTS, name)))["sensitivity_adjudication"]


def fmt(x, nd=0):
    return f"{x:,.{nd}f}"


def main():
    area = load("area_estimation.json")
    efg = load("area_estimation_efg.json")
    cont = load("ppi_continuous.json")
    deg = load("degradation_index.json")

    qa = area["ARP"]["inputs"]["qa_agreement"]
    A = area["ARP"]["inputs"]["area_total_ha"]

    css = """
    body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;max-width:1100px;
         margin:2rem auto;padding:0 1rem;color:#1a1a1a;line-height:1.5}
    h1{font-size:1.7rem} h2{margin-top:2.2rem;border-bottom:2px solid #eee;padding-bottom:.3rem}
    table{border-collapse:collapse;width:100%;margin:1rem 0;font-size:.92rem}
    th,td{border:1px solid #ddd;padding:.4rem .6rem;text-align:right} th{background:#f5f5f5}
    td:first-child,th:first-child{text-align:left}
    .note{background:#fff8e1;border-left:4px solid #f5b301;padding:.7rem 1rem;margin:1rem 0}
    .good{background:#e8f5e9;border-left:4px solid #43a047;padding:.7rem 1rem;margin:1rem 0}
    .no{color:#b00} .yes{color:#080} caption{font-weight:600;text-align:left;margin:.3rem 0}
    small{color:#666}
    """

    parts = [f"<h1>Thicket condition &mdash; design-based area estimation</h1>",
             f"<p><small>Auto-generated by analysis/20_report.py. Total mapped domain: "
             f"{fmt(A)} ha. n = {area['ARP']['inputs']['n_unique_points']} unique reference "
             f"points (deduplicated from 474 rows).</small></p>"]

    parts.append('<div class="note"><b>Reference-label QA.</b> '
                 f"{qa['n_duplicated']} points were deliberately double-labelled; "
                 f"{qa['n_agree']}/{qa['n_duplicated']} agreed. The "
                 f"{qa['n_disagree']} disagreements (ids "
                 f"{', '.join(str(d['id']) for d in qa['disagreements'])}) are resolved "
                 "two ways &mdash; keep ARP's or keep SVM's label &mdash; and BOTH are "
                 "reported below as an interpreter-variability sensitivity (Olofsson 2014).</div>")

    parts.append('<div class="good"><b>Headline (corrected).</b> With the proper '
                 "stratified variance as the baseline and the population probability "
                 "sample calibrated to the known mapped areas, PPI++ does <b>not</b> "
                 "tighten the intervals below the design-based estimator for any estimand "
                 "&mdash; area-by-class, area-by-EFG, or the continuous degradation index. "
                 "The Olofsson stratified estimator remains the primary estimator. The "
                 "earlier &ldquo;36&ndash;48% PPI improvement&rdquo; was an artifact of "
                 "comparing against an IID (non-stratified) variance and is withdrawn.</div>")

    # --- 1. area by class ---
    parts.append("<h2>1. Area by condition class (Olofsson vs PPI vs proper stratified)</h2>")
    for adj in ("ARP", "SVM"):
        for tag, sc in area[adj]["scenarios"].items():
            o = sc["olofsson"]
            parts.append(f'<table><caption>Adjudicate {adj} &mdash; {tag} '
                         f'(nothicket &rarr; {sc["nothicket_mode"]}, n={sc["n_used"]}, '
                         f'OA={o["overall_accuracy"]["OA"]:.3f})</caption>'
                         "<tr><th>class</th><th>Olofsson area (ha)</th><th>&plusmn;95%</th>"
                         "<th>stratified SE (ha)</th><th>PPI SE (ha)</th><th>PPI beats?</th></tr>")
            for k in sc["ref_classes"]:
                oa = o["area_ha"][k]; pk = sc["ppi_pp"][k]
                beats = pk["ppi_beats_stratified"]
                parts.append(
                    f"<tr><td>{k}</td><td>{fmt(oa['area'])}</td><td>{fmt(Z*oa['se'])}</td>"
                    f"<td>{fmt(pk['stratified']['se']*A)}</td>"
                    f"<td>{fmt(pk['ppi']['se_implied']*A)}</td>"
                    f"<td class='{'yes' if beats else 'no'}'>{'yes' if beats else 'no'}</td></tr>")
            parts.append("</table>")

    # --- 2. degradation index (headline estimand for PPI) ---
    parts.append("<h2>2. Continuous degradation index (PPI's best-case estimand)</h2>")
    parts.append("<p><small>D = 0&middot;p_intact + 0.5&middot;p_moderate + 1&middot;p_severe. "
                 "This is where PPI should help most; it still does not beat the stratified "
                 "baseline.</small></p>")
    for adj in ("ARP", "SVM"):
        for tag, sc in deg[adj]["scenarios"].items():
            parts.append(f'<table><caption>Adjudicate {adj} &mdash; {tag}</caption>'
                         "<tr><th>domain</th><th>n</th><th>stratified D</th><th>&plusmn;95%</th>"
                         "<th>PPI D</th><th>&plusmn;95%</th><th>PPI beats?</th><th>corr</th></tr>")
            def row(name, d):
                if d is None:
                    return f"<tr><td>{name}</td><td colspan=7>n/a</td></tr>"
                s, p = d["stratified"], d["ppi"]
                beats = d["ppi_beats_stratified"]
                return (f"<tr><td>{name}</td><td>{d['n']}</td>"
                        f"<td>{s['D']:.3f}</td><td>{Z*s['se']:.3f}</td>"
                        f"<td>{p['D']:.3f}</td><td>{Z*p['se']:.3f}</td>"
                        f"<td class='{'yes' if beats else 'no'}'>{'yes' if beats else 'no'}</td>"
                        f"<td>{d['calib']['corr_pred_true']:.2f}</td></tr>")
            parts.append(row("Overall", sc["overall"]))
            for e in ("Arid", "Valley", "Mesic"):
                parts.append(row(e, sc["efg"][e]))
            parts.append("</table>")

    # --- 3. EFG estimability ---
    parts.append("<h2>3. Area by EFG &times; class &mdash; estimability</h2>")
    for adj in ("ARP",):  # estimability identical across adjudication; show one
        for tag, sc in efg[adj]["scenarios"].items():
            parts.append(f'<table><caption>Adjudicate {adj} &mdash; {tag}</caption>'
                         "<tr><th>EFG</th><th>n labelled</th><th>estimable?</th>"
                         "<th>non-estimable cells</th></tr>")
            for e in ("Arid", "Valley", "Mesic"):
                pe = sc["per_efg"][e]
                est = pe["estimable"]
                cells = pe["non_estimable_cells"] or "&mdash;"
                parts.append(f"<tr><td>{e}</td><td>{pe['n_labelled']}</td>"
                             f"<td class='{'yes' if est else 'no'}'>{'OK' if est else 'NO'}</td>"
                             f"<td>{cells}</td></tr>")
            parts.append("</table>")
    parts.append('<div class="note">Mesic&ndash;severe (cell 32) has n=3 vs a planned '
                 "target of 129; its per-cell estimate is flagged low-n. Cells with n&lt;2 "
                 "are non-estimable and blocked from reporting (review Finding 5).</div>")

    doc = (f"<!doctype html><html><head><meta charset='utf-8'>"
           f"<title>Thicket area estimation</title><style>{css}</style></head>"
           f"<body>{''.join(parts)}</body></html>")
    outp = os.path.join(RESULTS, "area_estimation_report.html")
    open(outp, "w", encoding="utf-8").write(doc)
    print("wrote", outp)


if __name__ == "__main__":
    main()
